#!/usr/bin/env python

import sys

from rqt_rpc.rpc_module_real import RPCPlugin
from rqt_gui.main import Main

plugin = 'rqt_rpc_robot'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
